### ISSUE TITLE
Docker expose port incorrect and healthcheck fails

### ISSUE THREAD

**Issue by carsonxyz** [spritsail/lidarr#1]
The dockerfile is failing healthcheck since it exposes port `8689`, but runs the healtcheck against `8686`. I would suggest changing the exposed port to the default of `8686`. 

Thank you for this repo.

**Comment by frebib** [comment]
Huh, that must have been a merge oversight. I'll fix it today :)

**Comment by frebib** [comment]
The Dockerfile is wrong, but the exposed port doesn't at all affect the healthcheck, so if it is failing for you then there is another problem. Take a look at `docker inspect lidarr` and try to identify what the error is. If you post it here I can probably help

**Comment by carsonxyz** [comment]
I was able to solve it myself by adjusting the port. I use [Traefik](https://traefik.io/) to proxy my docker containers, and it's healcheck system was failing due to the mismatch. Thanks for having a look. I just thought I'd bring it up incase anyone else was having the same issue. Cheers!

**Comment by frebib** [comment]
Did you change the listening port of Lidarr? I was considering updating the healthcheck to read lidarr's port bind from the config file but I figured that very few users would want to change it because they can just use the port mapping with iptables that Docker provides for bridged networks?

**Comment by carsonxyz** [comment]
I think the change you have already made will cover most users, as it also fixed the issue for me. We can consider this issue closed and resolved.
